version: '3.9'

services:
  database_rentax:
    image: postgres
    container_name: database_rentax
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rentax
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentax
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/src/app
    links:
      - database_rentax
    depends_on:
      - database_rentax

volumes:
  pgdata: 
    driver: local
